In [1]:
from IPython.core.display import display, HTML
display(HTML(
"""<style>
div.container { width:100% !important; }
div.CodeMirror {font-family: Consolas; font-size: 30pt;}
div.output { font-size: 20pt; font-weight: bold;}
div.input { font-family: Consolas; font-size: 30pt;}
div.prompt { min-width: 100px;}
</style>
"""))

C:\Users\HKEDU\AppData\Local\Temp\ipykernel_9776\1014303460.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


In [7]:
### 변수, 상수, 함수을 묶어 놓은 것을 class
a = 1
def f(x): # 함수
    return 3 * x + 4

class Calculator:
    result = 10
    def add(self,num): # 메서드
        self.result += num
    

In [8]:
cal = Calculator() # result, add()
print(cal.result)
cal.add(10)
print(cal.result)

10
20


In [9]:
cal1 = Calculator() # result , add()
cal1.add(100)
print(cal1.result)
print(cal.result)

110
20


In [ ]:
cal2 = Calculator()

In [ ]:
result = 10
result += 11
result += 12
result += 13
result += 14


In [14]:
result = 10
def add(num):
    global result
    result += num

In [15]:
add(11)
add(12)
add(13)
add(14)
print(result)

60


In [ ]:
result1 = 100
result1 += 101
result1 += 102
result1 += 103
result1 += 104


In [16]:
result1 = 100
def add1(num):
    global result1
    result1 += num

In [17]:
add1(101)
add1(102)
add1(103)
add1(104)
print(result1)

510


In [22]:
# class내에 있는 함수의 매개변수 self
class ClassTest:
    result = 10 # 멤버필드, 멤버변수
    def add(self,num): # 객체변수 누구의  멤버인지를 알려주기 위해 self
        self.result += num # self는 자바의 this와 같다.

In [23]:
cal3 = ClassTest() # result, add()
cal4 = ClassTest() # result, add()

In [25]:
cal3.add(10) # ClassTest.add(cal3, 10)
print(cal3.result)
ClassTest.add(cal3, 10)
print(cal3.result)

30
40


In [27]:
cal4.add(100) # ClassTest.add(cal4, 100)
print(cal4.result)

210


In [42]:
# 멤버 필드 초기화
class FourCal: # 자바에서는 멤버필드를 명시해야 하지만 파이썬은 암시적으로 존재한다.
    #first
    #second
    #result
    def setData(self,num1, num2):
        self.first = num1
        self.second= num2
    def add(self):
        self.result = self.first + self.second
    def sub(self):
        self.result = self.first - self.second

In [43]:
cal5 = FourCal()
cal5.setData(10, 20)
print(cal5.first)
print(cal5.second)
cal5.add()
print(cal5.result)
cal5.sub()
print(cal5.result)

10
20
30
-10


In [45]:
cal6 = FourCal()
cal6.setData(10, 20)
cal6.add()

In [52]:
class FourCal:
    def __init__(self,num1, num2): # 생성자
        self.first = num1
        self.second= num2
    def add(self):
        self.result = self.first + self.second
    def div(self):
        self.result = self.first / self.second  

In [51]:
cal7 = FourCal(10, 20)
cal7.add()
print(cal7.result)
## __init__함수 : 생성자 : 객체가 생성이 될때 자동으로 실행되는 메서드
###                       객체내에 있는 멤버필드를 초기화 시켜준다.

30


In [74]:
# 상속
class MoreFourCal(FourCal):
    '''
    def __init__(self,num1, num2): # 생성자
        self.first = num1
        self.second= num2
    def add(self):
        self.result = self.first + self.second
    def div(self):
        self.result = self.first / self.second  
    '''
    def sub(self):
        self.result = self.first - self.second
    def mul(self):
        self.result = self.first * self.second
    def div(self): # 오버라이딩 : 재정의
        if self.second == 0:
            self.result = 0
        else:
            self.result = self.first / self.second

In [56]:
cal8 = MoreFourCal(20,10)
cal8.add()
print(cal8.result)
cal8.mul()
print(cal8.result)
cal8.div()
print(cal8.result)

30
200
2.0


In [57]:
cal9 = MoreFourCal(0,10) # first = 0, second = 10
cal9.div() # 0 / 10 = 0 부정
print(cal9.result)

0.0


In [76]:
cal10 = MoreFourCal(10, 0) # first = 10, second = 0
cal10.div() # 10 / 0 : 불능
print(cal10.result)

0


In [80]:
# 모듈 : 변수, 상수, 함수 , class를 하나로 모아둔 파일 mod1.py
import mod1
aaa = mod1.sum11(10, 20)
print(aaa)
cal13 = mod1.MoreFourCal(10, 20)
cal13.add()
print(cal13.result)
print(mod1.PI)

30
30
3.141592


In [78]:
import random
num = random.randint(1, 10)
print(num)

3


In [82]:
from mod1 import PI, sum11
print(PI)
result = sum11(20,20)
print(result)

3.141592
40


In [83]:
from mod1 import *
dddd.add()
print(dddd.result)

110


8


9


[0 0 0 5 9 2]


[0, 0, 0, 5, 9, 2]
[0 0 0 5 9 2]
0
0
[0, 0]
[0 0]


[[4 3 4 5]
 [3 1 9 9]
 [2 0 5 6]]
[[9, 7, 4, 2], [9, 2, 2, 3], [9, 4, 0, 8]]
0
5
4
0


[0 0 0 5 9 2]
[0, 0, 0, 5, 9, 2]
5
5
5
5
[0, 0, 5, 9]
[0 0 5 9]
[0, 0, 0, 5, 9, 2]
[0 0 0 5 9 2]
[0, 0, 9]
[0 0 9]
[0, 0, 9]
[0 0 9]
[2, 9, 5, 0, 0, 0]
[2 9 5 0 0 0]
[0, 0, 0, 10, 9, 2]
[ 0  0  0 10  9  2]


[[9, 7, 4, 2], [9, 2, 2, 3], [9, 4, 0, 8]]
[[4 3 4 5]
 [3 1 9 9]
 [2 0 5 6]]
2
9
9
2
9
9


[2 0 3 0]
[[2 4 1 3]]
[[[7 9 8 7]]]
0
4
9


[[9, 7, 4, 2], [9, 2, 2, 3], [9, 4, 0, 8]]
[[4 3 4 5]
 [3 1 9 9]
 [2 0 5 6]]
[9, 2, 2, 3]
[3 1 9 9]
[2, 2]
[1 9]
[1 9]
[[9, 7, 4, 2], [9, 2, 2, 3]]
[[4 3 4 5]
 [3 1 9 9]]


[9, 2]
[3 1]
[[9, 10, 4, 2], [9, 2, 2, 3]]
[[ 4 10  4  5]
 [ 3  1  9  9]]
[[10  4]
 [ 1  9]]
[[3 1 9 9]]
[[9, 2, 2, 3]]
[9, 4]
[4 4]
[4 4]
[[9, 10, 4, 2]]
[[ 4 10  4  5]]
[[4 4]
 [2 5]]
[[4 4]
 [3 9]
 [2 5]]
[[ 4 10  4  5]
 [ 2  0  5  6]]
[[9, 4, 0, 8], [9, 2, 2, 3], [9, 10, 4, 2]]
[[ 2  0  5  6]
 [ 3  1  9  9]
 [ 4 10  4  5]]
[[9, 10, 4, 2], [9, 2, 2, 3], [9, 4, 0, 8]]
[[9, 4, 0, 8], [9, 2, 2, 3], [9, 10, 4, 2]]
[[ 2  0  5  6]
 [ 3  1  9  9]
 [ 4 10  4  5]]
[[ 5  4 10  4]
 [ 9  9  1  3]
 [ 6  5  0  2]]
[[ 4 10  4  5]
 [ 3  1  9  9]
 [ 2  0  5  6]]
[[ 6  5  0  2]
 [ 9  9  1  3]
 [ 5  4 10  4]]
[9, 10, 4, 2]
[ 4 10  4  5]
[4 3 2]
[4 9 5]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [178]:
#3. array함수를 이용하는 방법
i6 = np.array([2,4,5])
print(i6)
i6 = np.array((2,4,5))
print(i6)
i7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(i7)
i8 = np.array(
    [[[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]]   
    ])
print(i8)
print(i6[2]) # [열]
print(i7[1,2]) # [행, 열]
print(i8[0,1,2]) # [면, 행, 열]

[2 4 5]
[2 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [179]:
ll1 = [1,2,3]
ll2 = [4,5,6]
ll3 = ll1 + ll2
print(ll3)

[1, 2, 3, 4, 5, 6]


In [188]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = array1 + array2
print(array3) # 배열에서는 열끼리 덧셈 연산
array3 = np.concatenate((array1 , array2))
print(array3)
print(array1)
print(array2)
z = [7,8,9]
array3 = np.concatenate((array1 , array2, z))
print(array3)
array3 = np.concatenate(([1,2,3] , [4,5,6], [7,8,9]))
print(array3)
array3 = np.concatenate(([1,2,3] , [4], [8,9]))
print(array3)

[5 7 9]
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 8 9]


In [196]:
x2 = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], 
                 [6, 5, 4]])
grid1 = np.array([[9, 8, 7], 
                 [6, 5, 4]])

# z = np.concatenate((x2,grid1), axis=0)
# 차원의 크기가 같아야 한다.]
z = np.concatenate((grid,grid1)) # axis=0은 기본값
print(z)
z = np.concatenate((grid,grid1), axis=0)
print(z)
z = np.concatenate((grid,grid1), axis=1)
print(z)
# 차원이 서로 다른 경우
z = np.vstack([grid,x2])
print(z)
x3 = [[10],[20]]
z = np.hstack([grid,x3])
print(z)

[[9 8 7]
 [6 5 4]
 [9 8 7]
 [6 5 4]]
[[9 8 7]
 [6 5 4]
 [9 8 7]
 [6 5 4]]
[[9 8 7 9 8 7]
 [6 5 4 6 5 4]]
[[9 8 7]
 [6 5 4]
 [1 2 3]]
[[ 9  8  7 10]
 [ 6  5  4 20]]
