In [3]:
### python 기본자료형 : 정수, 실수, 문자열, 부울, 리스트, 튜플, 딕셔너리(map), 집합
###### numpy ##### 숫자 배열
import numpy
num = numpy.random.randint(10)
print(num)

3


In [4]:
import numpy as np
num = np.random.randint(10)
print(num)

1


In [ ]:
# 1차원 배열 (0 ~ 9사이의 값을 가지는 )
num1 = np.random.randint(10, size=6) #크기 6인 1차원 배열
print(num1)

In [ ]:
l = [0,0,0,5,9,2]
print(l) # [0, 0, 0, 5, 9, 2]
#           0  1  2  3  4  5
print(num1) # [0 0 0 5 9 2] 
#              0 1 2 3 4 5
print(l[0])
print(num1[0])
print(l[1:3])
print(num1[1:3])

In [ ]:
# 2차원
num2 = np.random.randint(10, size=(3,4))
print(num2) #[[9 7 4 2][9 2 2 3][9 4 0 8]]
#                 0         1        2
#              0 1 2 3  0 1 2 3  0 1 2 3
l2 = [[9, 7, 4, 2],[9, 2, 2, 3],[9, 4, 0, 8]]
#          0            1            2
#         -3            2            1
#      0  1   2  3  0  1  2  3   0  1  2  3
#     -4  3   2  1  4  3  2  1   4  3  2  1
print(l2)
print(l2[2][2])
print(num2[2][2])
print(l2[-1][-3])
print(num2[-1][-3])

In [ ]:
# [0 0 0 5 9 2]
#  0 1 2 3 4 5
# -6 5 4 3 2 1
print(num1)
print(l)
print(num1[3])
print(num1[-3])
print(l[3])
print(l[-3])
## slicing
print(l[1:1+4])
print(num1[1:1+4])
print(l[0:6])
print(num1[0:6])
print(l[0:6:2])
print(num1[0:6:2])
print(l[::2])
print(num1[::2])
print(l[::-1])
print(num1[::-1])
l[3] = 10
num1[3] = 10
print(l)
print(num1)

In [ ]:
print(l2)
# [[9, 7, 4, 2], [9, 2, 2, 3], [9, 4, 0, 8]]
#       0              1             2             :index
#    -  3              2             1
#   0  1  2  3    0  1  2  3    0  1  2  3         :index
#  -4  3  2  1    4  3  2  1    4  3  2  1
print(num2)
# [[4 3 4 5][3 1 9 9][2 0 5 6]]
#      0        1        2       : 행
#   0 1 2 3  0 1 2 3  0 1 2 3    : 열
#[[4 3 4 5]     0행
# [3 1 9 9]     1행
# [2 0 5 6]]    2행
#  1 2 3 4열
print(l2[1][2])
print(num2[1][2]) 
print(num2[1 , 2]) # [행,열]
#print(l2[1, 2])
print(l2[-2][-2])
print(num2[-2][-2])
print(num2[-2, -2])

In [ ]:
n1 = np.random.randint(10, size=4) # 1차원배열
n2 = np.random.randint(10, size=(1,4)) # 2차원배열
n3 = np.random.randint(10, size=(1,1,4)) # 3차원배열
print(n1) # [6 6 4 2]
print(n2) # [[7 2 4 6]]
print(n3) # [[[6 0 4 9]]]
print(n1[1])
print(n2[0,1])
print(n3[0,0,1])

In [ ]:
print(l2)
# [[9, 7, 4, 2], 
#  [9, 2, 2, 3], 
#  [9, 4, 0, 8]]
print(num2)
# [[4 3 4 5]
# [3 1 9 9]
# [2 0 5 6]]
print(l2[1]) # [9, 2, 2, 3]
print(num2[1]) # [3 1 9 9]
print(l2[1][1:3])
print(num2[1][1:3])
print(num2[1, 1:3])
print(l2[0:2])
print(num2[0:2])

In [ ]:
''' l2, num2
[[9, 7, 4, 2], 
 [9, 2, 2, 3], 
 [9, 4, 0, 8]]
'''
print(l2[1][0:2])
print(num2[1][0:2])
print(l2[0:2])
print(num2[0:2])
print(num2[0:2, 1:3]) # [[3 4][1 9]]
print(num2[0:2][1:3]) # [[3 1 9 9]]
print(l2[0:2][1:3]) # [[3 1 9 9]]
print(l2[0][::2])
print(num2[0][::2])
print(num2[0, ::2])
print(l2[::2][::2]) #[[9, 7, 4, 2]]
print(num2[::2][::2]) #[[4 3 4 5]]
print(num2[::2, ::2]) # [[4 4][2 5]]
### 모든 행에서 열을 한칸씩 건너 띄우기
print(num2[: , ::2])
### 행을 한칸씩 건너 띄우고 열은 모두 출력
print(num2[::2, :])


print(l2[::-1])
print(num2[::-1])

print(l2)
print(l2[:][::-1])
print(num2[:][::-1])
print(num2[: , ::-1])

print(num2)
print(num2[::-1, ::-1])

print(l2[:][0])
print(num2[:][0])
print(num2[: , 0])
print(num2[: , 2])
l2[0][1] = 10
num2[0][1] = 10
num2[0, 1] = 10

In [ ]:
### 배열을 만드는 3가지 방법
##1. random함수를 이용하는 방법
i = np.random.randint(10, size=(2,3))
##2. arange함수를 이용하는 방법
i2 = np.arange(9).reshape(3, 3)
print(i2)
#i2 = np.arange(9).reshape(2,3)

i3 = np.arange(12).reshape(3,4)
print(i3)
i3 = np.arange(12).reshape(4,3)
print(i3)

i4 = np.arange(11,20).reshape(3,3)
print(i4)

# 1~3까지의 수를 가지는 1행짜리 2차원배열
i5 = np.arange(1, 4).reshape(1,3)
print(i5)
# 1~3까지의 수를 가지는 3행짜리 2차원배열
i5 = np.arange(1, 4).reshape(3,1)
print(i5)

In [ ]:
#3. array함수를 이용하는 방법
i6 = np.array([2,4,5])
print(i6)
i6 = np.array((2,4,5))
print(i6)
i7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(i7)
i8 = np.array(
    [[[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]]   
    ])
print(i8)
print(i6[2]) # [열]
print(i7[1,2]) # [행, 열]
print(i8[0,1,2]) # [면, 행, 열]

In [ ]:
ll1 = [1,2,3]
ll2 = [4,5,6]
ll3 = ll1 + ll2
print(ll3)

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = array1 + array2
print(array3) # 배열에서는 열끼리 덧셈 연산
array3 = np.concatenate((array1 , array2))
print(array3)
print(array1)
print(array2)
z = [7,8,9]
array3 = np.concatenate((array1 , array2, z))
print(array3)
array3 = np.concatenate(([1,2,3] , [4,5,6], [7,8,9]))
print(array3)
array3 = np.concatenate(([1,2,3] , [4], [8,9]))
print(array3)

In [5]:
x2 = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], 
                 [6, 5, 4]])
grid1 = np.array([[9, 8, 7], 
                 [6, 5, 4]])

# z = np.concatenate((x2,grid1), axis=0)
# 차원의 크기가 같아야 한다.]
z = np.concatenate((grid,grid1)) # axis=0은 기본값
print(z)
z = np.concatenate((grid,grid1), axis=0)
print(z)
z = np.concatenate((grid,grid1), axis=1)
print(z)
# 차원이 서로 다른 경우
z = np.vstack([grid,x2])
print(z)
x3 = [[10],[20]]
z = np.hstack([grid,x3])
print(z)

[[9 8 7]
 [6 5 4]
 [9 8 7]
 [6 5 4]]
[[9 8 7]
 [6 5 4]
 [9 8 7]
 [6 5 4]]
[[9 8 7 9 8 7]
 [6 5 4 6 5 4]]
[[9 8 7]
 [6 5 4]
 [1 2 3]]
[[ 9  8  7 10]
 [ 6  5  4 20]]
